sudo: false
language: java
jdk:
  - openjdk7
  - oraclejdk8
env:
  - SPRING_VERSION=3.2.14.RELEASE
  - SPRING_VERSION=4.0.9.RELEASE
  - SPRING_VERSION=4.1.7.RELEASE
  - SPRING_VERSION=4.2.0.RELEASE

# Cache local Maven repository.
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -Rf $HOME/.m2/repository/cz/jirutka/spring/spring-rest-exception-handler

install:
  - mvn install -Dspring.version=$SPRING_VERSION -DskipTests=true --batch-mode
script:
  - mvn verify -Dspring.version=$SPRING_VERSION --batch-mode
after_success:
  - 'mvn jacoco:report coveralls:jacoco'
