sudo: false
language: java
jdk:
  - openjdk7
  - oraclejdk8
env:
  global:
    secure: "DiliRHV1VROi28XVoFVupupLMVJ0IqyuJsBR2NyfjhAB4eOvwyRY78H2iNzZ5TPkgQ2x5roCE9vDF4WRlRGd/rTgs2YvRjCL2tOpjxYXgyjuFKq0HtnG6Jpr45LV7dmTxiAUXjiNUa9SSr30CXAOEM2dcPYjci3Ze7HV/5BtkSU="  # BINTRAY_API_KEY
  matrix:
    - SPRING_VERSION=3.2.16.RELEASE
    - SPRING_VERSION=4.0.9.RELEASE
    - SPRING_VERSION=4.1.9.RELEASE
    - SPRING_VERSION=4.2.4.RELEASE

# Cache local Maven repository.
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -Rf $HOME/.m2/repository/cz/jirutka/spring/spring-rest-exception-handler

install:
  - mvn install -Dspring.version=$SPRING_VERSION -DskipTests=true --batch-mode
script:
  - mvn verify -Dspring.version=$SPRING_VERSION --batch-mode
after_success:
  - mvn jacoco:report coveralls:report
  - script/travis-deploy
